#%RAML 0.8
---
title: humgen API
documentation:
    - title: humgen REST API
      content: |
        Welcome to the humgen API.
baseUri: http://{host}:{port}/{version}
version: v1
mediaType: application/json
protocols: [HTTP]

/ihdi_countries:
    displayName: Collection of IHDI country entries
    get:
        description: Get all IHDI country entries
    post:
        description: Create a new IHDI country entry
        body:
            application/json:
                schema: !include schemas/ihdi.json

    /{country}:
        displayName: One IHDI country entry
        get:

/gii_countries:
    displayName: Collection of GII country entries
    get:
        description: Get all GII country entries
    post:
        description: Create a new GII country entry
        body:
            application/json:
                schema: !include schemas/gii.json

    /{country}:
        displayName: One GII country entry
        get:

/combined_inequalities
    displayName: Collection of combined index values for plotting IHDI/GII
    get:
        description: Get all combined IHDI/GII index value coordinates
    post:
        description: Create a new combined country entry
        body:
            application/json:
                schema: !include schemas/combined_inequalities.json
    
    /{country}
        displayName: One combined country entry
    